# Generated by Django 5.2 on 2025-04-25 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='test_cases',
            new_name='invisible_test_cases',
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attempt',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='test_case_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='visible_test_cases',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('contest', 'student', 'is_final')},
        ),
    ]
