# Generated by Django 5.2 on 2025-05-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="options",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
