# Generated by Django 5.2 on 2025-04-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_rename_test_cases_question_invisible_test_cases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='language',
        ),
    ]
