# Generated by Django 5.2 on 2025-04-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_remove_question_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
