# Generated by Django 5.2 on 2025-04-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='back_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='fullscreen_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
